include: [assets/css, assets/js/main.js]
keep_files: [assets/css, assets/js/main.js]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"