name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
      - test-new-help
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./help
          enable_jekyll: true

